name: pipelineNel

on:
  workflow_dispatch:
    inputs:
      lenguaje:
        description: 'Lenguaje de programaci√≥n'
        required: true

jobs:
  imprimir:
    runs-on: ubuntu-latest
    steps:
      - name: mensaje
        run: echo "Hola mundo"
